<a href="https://colab.research.google.com/github/Danish-2025/data_science_v1/blob/main/Tutorial_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
array_2x2 = np.array([[1, 2], [3, 4]])
print(array_2x2)

[[1 2]
 [3 4]]


In [8]:
random_3x4 = np.random.rand(3, 4)
print(random_3x4)

[[0.89416918 0.55139474 0.46166743 0.93726606]
 [0.14978425 0.25307838 0.08567509 0.91788596]
 [0.07075722 0.57542237 0.13461552 0.52767423]]


In [9]:
ones_array = np.ones((2, 3))
zeroes_array = np.zeros((3, 2))
print(ones_array, zeroes_array)

[[1. 1. 1.]
 [1. 1. 1.]] [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
arr_6x3 = np.random.rand(6, 3)
transposed_arr = arr_6x3.T  # or np.transpose(arr_6x3)
print(transposed_arr.shape) # Result will be (3, 6)

(3, 6)


In [11]:
n, p, m = 3, 4, 2
matrix_A = np.random.rand(n, p)
matrix_B = np.random.rand(p, m)

dot_product = np.dot(matrix_A, matrix_B)
# Alternatively: dot_product = matrix_A @ matrix_B
print(dot_product.shape) # Result will be (n, m)

(3, 2)
